language: generic

sudo: required

matrix:
  include:
    - dist: trusty
      env: COQ_VERSION="8.5pl2" COQ_PACKAGE="coq-8.5pl2 libcoq-ocaml-8.5pl2" PPA="ppa:jgross-h/many-coq-versions"
    - dist: trusty
      env: COQ_VERSION="8.5"    COQ_PACKAGE="coq-8.5"                        PPA="ppa:jgross-h/many-coq-versions"
    - dist: precise
      env: COQ_VERSION="8.4pl6" COQ_PACKAGE="coq-8.4pl6 libcoq-ocaml-8.4pl6" PPA="ppa:jgross-h/many-coq-versions-ocaml-3-temp-while-over-quota-2"
    - dist: precise
      env: COQ_VERSION="8.4pl1" COQ_PACKAGE="coq-8.4pl1 libcoq-ocaml-8.4pl1" PPA="ppa:jgross-h/many-coq-versions-ocaml-3-temp-while-over-quota-2"
    - dist: trusty
      env: COQ_VERSION="8.4"    COQ_PACKAGE="coq"        PPA=""

before_install:
  - if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
  - sudo apt-get update -q
  - sudo apt-get install $COQ_PACKAGE -y

script: coqc bug_4901.v
